Repository ManageIQ/miq_bot, pull requests merged in 2020-11, with the labels that each got.

#527 Fix container build issues
  Dockerfile
Labels: bug

#528 Simplify creating the branch records
  app/models/branch.rb
Labels: enhancement

#530 Fix testing Net::HTTP response code
  lib/github_service/commands/cross_repo_test.rb
  spec/lib/github_service/commands/cross_repo_test_spec.rb
Labels: bug

#531 Update manageiq-style to v1.1.1
  Gemfile.lock
Labels: dependencies
