Repository ManageIQ/miq_bot, pull requests merged in 2020-10, with the labels that each got.

#454 Add cross_repo_test bot command
  .gitignore
  README.md
  lib/github_service/commands/cross_repo_test.rb
  spec/lib/github_service/commands/cross_repo_test_spec.rb
  spec/support/git_repo_helper.rb
Labels: enhancement

#506 Switch to using manageiq-style for linting dependencies
  .rubocop.yml
  Gemfile
  Gemfile.lock
Labels: dependencies, enhancement

#520 Fix the /opt/opt/miq_bot issue
  Dockerfile
Labels: bug

#521 Update Travis to the same ruby installed on the bot
  .travis.yml
Labels: test

#523 Fixes for running from master
  Dockerfile
Labels: bug

#524 For cross-repo-test, make PR Name more specific
  lib/github_service/commands/cross_repo_test.rb
  spec/lib/github_service/commands/cross_repo_test_spec.rb
Labels: enhancement
