Repository ManageIQ/miq_bot, pull requests merged in 2021-04, with the labels that each got.

#556 We haven't been using these metrics.
  app/workers/code_analyzer.rb
  app/workers/schedulers/code_analyzer.rb
Labels: cleanup

#557 [Linter::Base] Fix invalid .linter_env
  lib/linter/base.rb
  spec/lib/linter/base_spec.rb
  spec/lib/linter/haml_spec.rb
  spec/lib/linter/rubocop_spec.rb
Labels: bug

#555 Bump rails to 5.2.5
  Gemfile
  Gemfile.lock
Labels: dependencies

#558 Add shared-mime-info to Dockerfile
  Dockerfile
Labels: bug

#560 Update manageiq-style, including rubocop update
  Gemfile.lock
  app/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder.rb
  spec/support/rubocop_spec_helper.rb
  spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/data/.rubocop.yml
  spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/data/.rubocop_local.yml
  spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/data/with_haml_file_using_haml-lint/results.json
  spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/data/with_lines_not_in_the_diff/results.json
  spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/data/with_results_generating_multiple_comments/results.json
  spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/data/with_results_with_no_offenses/no_offenses.rb
  spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/data/with_results_with_no_offenses/results.json
  spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/data/with_results_with_offenses/no_offenses.rb
  spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/data/with_results_with_offenses/results.json
  spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/data/with_results_with_offenses/ruby_syntax_error.rb
  spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/data/with_results_without_column_numbers_and_cop_names/results.json
  spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/data/with_void_warnings_in_spec_files/results.json
  spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder_spec.rb
Labels: enhancement

#561 Use RuboCop::Cop::Base#documentation_url directly
  app/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder.rb
  spec/support/rubocop_spec_helper.rb
  spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder_spec.rb
Labels: enhancement
