Repository ManageIQ/miq_bot, pull requests merged in 2022-08, with the labels that each got.

#606 Warn users about merge commits in PRs
  app/workers/commit_monitor_handlers/commit_range/github_pr_commenter/commit_metadata_checker.rb
  spec/workers/commit_monitor_handlers/commit_range/github_pr_commenter/commit_metadata_checker_spec.rb
Labels: enhancement

#607 Build rugged with SSH support
  Dockerfile
  Gemfile.lock
Labels: bug

#608 Downgrade sidekiq to 5.2.9
  Gemfile
  Gemfile.lock
Labels: bug, dependencies

#611 Replace Sidetiq with Sidecloq
  Gemfile
  Gemfile.lock
  app/workers/batch_job_monitor.rb
  app/workers/commit_monitor.rb
  app/workers/github_notification_monitor_worker.rb
  app/workers/pull_request_monitor.rb
  app/workers/schedulers/stale_issue_marker.rb
  app/workers/travis_build_killer.rb
  config/routes.rb
  config/sidecloq.yml
Labels: dependencies
