Repository ManageIQ/miq_bot, pull requests merged in 2023-11, with the labels that each got.

#655 Drop close issue
  app/workers/stale_issue_marker.rb
  spec/workers/stale_issue_marker_spec.rb
Labels: enhancement

#656 Various cleanup in the stale issue marker
  app/workers/stale_issue_marker.rb
Labels: cleanup

#657 Drop InfluxDB/Grafana support for the GithubUsageTracker
  Gemfile
  Gemfile.lock
  README.md
  config/settings.yml
  lib/github_service/response/ratelimit_logger.rb
  lib/github_usage_tracker.rb
  spec/lib/github_usage_tracker_spec.rb
Labels: technical debt

#661 More Grafana deletes
  app/helpers/application_helper.rb
  app/views/layouts/_navbar.html.erb
  config/settings.yml
  templates/bot.yaml
Labels: technical debt

#662 Drop TravisBuildKiller as we are no longer on travis
  app/workers/travis_build_killer.rb
Labels: technical debt

#663 Upgrade to Rails 6.1 / Ruby 2.7
  .github/workflows/ci.yaml
  .gitignore
  Dockerfile
  Gemfile
  Gemfile.lock
  Procfile.tmpl
  Vagrantfile
  app/models/batch_entry.rb
  app/models/batch_job.rb
  app/models/repo.rb
  app/workers/commit_monitor_handlers/commit_range/path_based_labeler.rb
  app/workers/pull_request_monitor_handlers/merge_target_titler.rb
  app/workers/pull_request_monitor_handlers/wip_labeler.rb
  bin/rails
  bin/rake
  bin/setup
  config.ru
  config/application.rb
  config/boot.rb
  config/cable.yml
  config/credentials.yml.enc
  config/database.yml.sample
  config/environment.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/application_controller_renderer.rb
  config/initializers/assets.rb
  config/initializers/backtrace_silencers.rb
  config/initializers/content_security_policy.rb
  config/initializers/cookies_serializer.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/mime_types.rb
  config/initializers/permissions_policy.rb
  config/initializers/secret_token.rb
  config/initializers/session_store.rb
  config/initializers/wrap_parameters.rb
  config/locales/en.yml
  config/puma.rb
  config/routes.rb
  config/storage.yml
  db/schema.rb
  lib/git_service/branch.rb
  lib/linter/base.rb
  lib/linter/haml.rb
  lib/miq_bot.rb
  spec/models/batch_job_spec.rb
  spec/spec_helper.rb
  spec/support/awesome_spawn_helper.rb
  spec/workers/concerns/batch_entry_worker_mixin_spec.rb
  spec/workers/pull_request_monitor_spec.rb
  systemd/miq_bot-sidekiq.service
  systemd/miq_bot-sidekiq_glacial.service
  systemd/miq_bot-thin.service
  systemd/miq_bot.service
Labels: enhancement, dependencies

#664 Add production settings
  config/settings/production.yml
Labels: enhancement

#665 Cleanup some production settings
  config/settings/production.yml
Labels: enhancement

#666 Update deployment logic for settings changes
  container-assets/entrypoint
  templates/bot.yaml
Labels: enhancement

#667 Fix the path to the files in the secret
  container-assets/entrypoint
Labels: bug

#448 Add bundle_inject
  Gemfile
  bundler.d/.gitkeep
Labels: enhancement

#670 Drop foreman:export rake task
  lib/tasks/foreman.rake
Labels: technical debt

#669 Update production cluster
  lib/tasks/production.rake
Labels: tools
