Repository ManageIQ/miq_bot, pull requests merged in 2024-06, with the labels that each got.

#690 Add production.rake helpers for IbmCloud
  lib/tasks/production.rake
Labels: enhancement

#691 Fix issue where tags with dashes are ignored
  app/models/branch.rb
  spec/models/branch_spec.rb
Labels: bug

#692 CentOS Stream 8 is EOL
  Dockerfile
Labels: dependencies

#693 Add GitHub Action to build and deploy
  .github/workflows/build_and_deploy.yml
  lib/tasks/production.rake
Labels: tools

#696 Bump rails to 6.1.7.8
  Gemfile
  Gemfile.lock
Labels: dependencies

#613 Upgrade Dockerfile to UBI9
  .github/workflows/build_and_deploy.yml
  .github/workflows/ci.yaml
  Dockerfile
  Gemfile
  Gemfile.lock
  app/workers/stale_issue_marker.rb
  lib/git_service/repo.rb
  lib/github_notification_monitor.rb
  lib/github_service/commands/cross_repo_test.rb
  spec/lib/github_notification_monitor_spec.rb
Labels: dependencies, pinned

#698 Allow loading YAML loading Dates
  lib/github_notification_monitor.rb
  spec/lib/github_notification_monitor_spec.rb
Labels: bug
