Repository ManageIQ/miq_bot, pull requests merged in 2025-03, with the labels that each got.

#775 Add database level uniqueness on branch records
  db/migrate/20250305205548_add_uniqueness_constraint_on_branches.rb
  db/schema.rb
  spec/models/branch_spec.rb
Labels: bug

#770 Upgrade to Rails 7.0 with rake app:update
  Gemfile
  Gemfile.lock
  bin/rails
  bin/setup
  config/application.rb
  config/boot.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/assets.rb
  config/initializers/content_security_policy.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  db/schema.rb
Labels: dependencies

#778 Add support for a VERSION file
  Dockerfile
  config/application.rb
  spec/miq_bot_spec.rb
Labels: enhancement

#777 Check version format during release
  lib/tasks/production.rake
Labels: bug

#797 Don't include newer openssl packages from CentOS Stream
  Dockerfile
Labels: bug
